#!/usr/bin/env python3
"""Export public reference data into an importable SQLite seed SQL file.

The default paths deliberately point at the repository's canonical public
database and generated content package.  Optional arguments make it possible
to export a different template database when preparing a release.
"""

from __future__ import annotations

import argparse
import math
import sqlite3
from pathlib import Path
from typing import Any


REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = REPOSITORY_ROOT / "data" / "public" / "public.db"
DEFAULT_OUTPUT = REPOSITORY_ROOT / "resources" / "sql" / "init-content.sql"

# This is a whitelist, not a dump of all tables.  Its order is a valid import
# order for every ordinary foreign key in the content package.
TABLES_IN_IMPORT_ORDER = (
    "label",
    "maker",
    "series",
    "tag_type",
    "tag",
    "prefix_maker_relation",
)


def quote_sql_value(value: Any) -> str:
    """Return a SQLite literal which preserves the Python sqlite value."""
    if value is None:
        return "NULL"
    if isinstance(value, bytes):
        return "X'" + value.hex() + "'"
    if isinstance(value, str):
        # SQLite's normal quoted strings cannot represent a NUL byte.  Hex is
        # exact in that uncommon case while keeping normal exports readable.
        if "\x00" in value:
            return "CAST(X'" + value.encode("utf-8").hex() + "' AS TEXT)"
        return "'" + value.replace("'", "''") + "'"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if not math.isfinite(value):
            raise ValueError(f"Cannot export non-finite floating-point value: {value!r}")
        return repr(value)
    raise TypeError(f"Unsupported SQLite value type: {type(value).__name__}")


def quote_identifier(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


def table_columns(connection: sqlite3.Connection, table: str) -> list[str]:
    rows = connection.execute(f"PRAGMA table_info({quote_identifier(table)})").fetchall()
    if not rows:
        raise RuntimeError(f"Required table is missing: {table}")
    return [row[1] for row in rows]


def export_table(connection: sqlite3.Connection, table: str) -> list[str]:
    columns = table_columns(connection, table)
    quoted_table = quote_identifier(table)
    quoted_columns = ", ".join(quote_identifier(column) for column in columns)
    rows = connection.execute(f"SELECT * FROM {quoted_table}").fetchall()

    statements = [f"-- {table}: {len(rows)} row(s)"]
    for row in rows:
        values = ", ".join(quote_sql_value(value) for value in row)
        statements.append(f"INSERT INTO {quoted_table} ({quoted_columns}) VALUES ({values});")
    return statements


def validate_foreign_keys(connection: sqlite3.Connection) -> None:
    violations = connection.execute("PRAGMA foreign_key_check").fetchall()
    if violations:
        formatted = ", ".join(
            f"table={table}, rowid={rowid}, parent={parent}, fk={fk}" 
            for table, rowid, parent, fk in violations[:10]
        )
        raise RuntimeError(f"Source database has foreign-key violations: {formatted}")


def verify_export(source: sqlite3.Connection, sql: str) -> None:
    """Import into an in-memory schema to catch ordering or escaping errors."""
    destination = sqlite3.connect(":memory:")
    try:
        for table in TABLES_IN_IMPORT_ORDER:
            schema = source.execute(
                "SELECT sql FROM sqlite_master WHERE type = 'table' AND name = ?", (table,)
            ).fetchone()[0]
            destination.execute(schema)
        destination.executescript(sql)
        destination.execute("PRAGMA foreign_keys = ON")
        violations = destination.execute("PRAGMA foreign_key_check").fetchall()
        if violations:
            raise RuntimeError(f"Generated SQL has foreign-key violations: {violations[:10]}")
        for table in TABLES_IN_IMPORT_ORDER:
            expected = source.execute(f"SELECT COUNT(*) FROM {quote_identifier(table)}").fetchone()[0]
            actual = destination.execute(f"SELECT COUNT(*) FROM {quote_identifier(table)}").fetchone()[0]
            if actual != expected:
                raise RuntimeError(f"Verification count mismatch for {table}: {actual} != {expected}")
    finally:
        destination.close()


def build_sql(connection: sqlite3.Connection, source: Path) -> str:
    validate_foreign_keys(connection)
    try:
        source_description = source.relative_to(REPOSITORY_ROOT).as_posix()
    except ValueError:
        source_description = source.as_posix()
    lines = [
        "-- Generated by tools/export_init_content.py. Do not edit by hand.",
        f"-- Source: {source_description}",
        "-- Import order respects foreign keys; deferred checks support tag redirects.",
        "BEGIN TRANSACTION;",
        "PRAGMA defer_foreign_keys = ON;",
        "",
    ]
    for table in TABLES_IN_IMPORT_ORDER:
        lines.extend(export_table(connection, table))
        lines.append("")
    lines.extend(("COMMIT;", ""))
    return "\n".join(lines)


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", nargs="?", type=Path, default=DEFAULT_SOURCE,
                        help=f"template SQLite database (default: {DEFAULT_SOURCE})")
    parser.add_argument("output", nargs="?", type=Path, default=DEFAULT_OUTPUT,
                        help=f"generated seed SQL path (default: {DEFAULT_OUTPUT})")
    return parser.parse_args()


def main() -> None:
    arguments = parse_arguments()
    source = arguments.source.resolve()
    output = arguments.output.resolve()
    if not source.is_file():
        raise SystemExit(f"Source database does not exist: {source}")

    connection = sqlite3.connect(f"file:{source.as_posix()}?mode=ro", uri=True)
    try:
        sql = build_sql(connection, source)
        verify_export(connection, sql)
    finally:
        connection.close()

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(sql, encoding="utf-8", newline="\n")
    print(f"Exported {len(TABLES_IN_IMPORT_ORDER)} tables to {output}")


if __name__ == "__main__":
    main()
